language: android
android:
  components:
    - build-tools-18.1.0
    - android-19

before_script:
# download and setup NDK
- wget http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2
- tar xf android-ndk-r9-linux-x86_64.tar.bz2
- sudo mv android-ndk-r9 /usr/local/android-ndk
# sym link because currently node-appc looks here
- sudo ln -s /usr/local/android-sdk /usr/android-sdk
- sudo ln -s /usr/local/android-ndk /usr/android-ndk
# setup grunt
- npm install -g grunt-cli
# Create and start emulator
- echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- ./wait_for_emulator

install:
- npm install

script:
- grunt test

notifications:
  flowdock:
    secure: WpU/gKxLHbneKEZPh2udTGa/qdV69LofoK0ffRjar0DvV1NAAfiCJUKLihhdtJ7QMX4Q7JTK4REom56xtaiakURoEI/qHBPcKyZKSKE1/IF4TGiL5FEXPSigurB115CXapQ1+c6ISBl2Vg8InQXmj3uFzmsCA3G8VYP+bT2WrVc=
